services:
  web:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=db;Database=blog;Username=ahmed;Password=12345;Port=5432
      - ConnectionStrings__Redis=redis:6379
      - Jwt__Key=YourSecretKeyHere1234567890AtLeast32Chars
      - Jwt__Issuer=BlogApp
      - Jwt__Audience=BlogApp
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - blogapp-network
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - blogapp-network
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - blogapp-network
volumes:
  pgdata:
  redisdata:
networks:
  blogapp-network:
    driver: bridge